#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
name = "Test_Project_4"
short_name = "pyconus_test4"
email = "cole@colewilson.xyz"
author = "Cole Wilson"
short_description = "short"
description = "long"
url = "https://google.com"
keywords = "kw1 kw2"
license = "none"
latest_build = "0.0.2"
release-notes = "Initial Release"
latest_release = "0.0.1"


# Resource Setup:
[resources]
icns = ""
data_files = []
modules = []
file = "main.py"
no_import = []


# Plugin Commands:


# Build Routines:
[build.homebrew]

[build.pyinstaller]
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.colewilson.pyconus_test4"

[build.actions]

[build.pypi.commands]
hello = ""

[build.pypi.entry_points]


# Release Routines:


# Other:
[git]
github = "cole-wilson/test4"
brew = "cole-wilson/homebrew-taps"


# Thank you for using Sailboat!